My Portofolio
Irirwanirira/My-portofolio pull request #1
Opened 2022-08-17 18:25 UTC by Irirwanirira

## My portfolio

In this project 
- I added a readme.file
- I added linters for error check
- I added HTML content 
- I added a CSS style

### Thank you for reviewing my project

2022-08-17 22:10 UTC, ha-manel requested changes
# STATUS: REQUIRED CHANGES ♻️

## Hi @Irirwanirira 👋🏻
Great job so far, There are some changes that need to be implemented in order to proceed to the next project 👍🏻 

<img src="https://media0.giphy.com/media/z3piokwf0WPH81MOhu/giphy.gif"/>

## Highlights:  
* All tests passed ✔️
* Meaningful commit messages ✔️ 
* Professional README file ✔️

## Required Changes:
_Please check the comments below for more changes_

------
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-17 22:10 UTC, ha-manel commented on index.html
> +            <p class="logo">My Logo</p>
- [x] Kindly change the `p` tag to an `a` tag. This is for three reasons: convention, semantics, and user experience(UX). [Check this link](https://ux.stackexchange.com/questions/81727/why-is-it-standard-for-a-website-logo-to-navigate-to-the-home-page) for more info.

2022-08-17 22:10 UTC, ha-manel commented on index.html
> +            <i class="fa-solid fa-bars"></i>
- [x] Kindly wrap the hamburger button in a `nav` tag. The `nav` tag is used for semantic reasons 💯

2022-08-17 22:10 UTC, ha-manel commented on index.html
> +                Glad to see you!</h2>
- [x] Kindly change the `h2` tag to an `h1` tag for accessibility reasons. [Check this link](https://www.reliablesoft.net/h1-tag/) for more info.

2022-08-17 22:10 UTC, ha-manel commented on index.html
> +            </div>
- [x] Kindly wrap the icons in a `ul` element, each icon should be an `a` tag wrapped in an `li` element. Apart from being semantically correct, the `a` tag will let you connect your social networks with the icons, using `href` ✍🏻

2022-08-17 22:10 UTC, ha-manel commented on style.css
> +  font-family: 'poppins', serif;
- [ ] Kindly use the same font family and font weights used in the template. You can import it from [Google fonts](https://fonts.google.com/specimen/Poppins?query=poppins) and you'll see a difference 💯

## Your design:
![image](https://user-images.githubusercontent.com/50721479/185251768-a86b4d1f-9bd1-46e5-95aa-e73788d22d4a.png)

## Figma design:
![image](https://user-images.githubusercontent.com/50721479/185251823-b8fb7ac8-817e-40ef-a7fd-fc2d67bba02b.png)

2022-08-17 22:10 UTC, ha-manel commented on style.css
> +  size: 18px;
- [ ] Kindly fix this mistake, it's `font-size` not size.

2022-08-17 22:10 UTC, ha-manel commented on style.css
> +  line-height: 16px;
- [ ] Kindly fix this mistake, it's `font-size` not `line-height` (line-height is 24px according to figma)

2022-08-17 22:10 UTC, ha-manel commented on style.css
> +  font-weight: 400px;
- [ ] Kindly fix this mistake, remove `px`. `font-weight` is not measured in px 👍🏻

2022-08-17 22:13 UTC, ha-manel commented on style.css
> +}
- [ ] Kindly update your design to make it match the Figma design 💯 

## Your design:
![image](https://user-images.githubusercontent.com/50721479/185252653-75b97da9-54a0-4843-b51a-94324a0bea12.png)

## Figma design:
![image](https://user-images.githubusercontent.com/50721479/185252691-dea134e7-a38c-44f8-a487-4ba777d3c8a1.png)

2022-08-18 08:32 UTC, HAMMAS-SALEEM requested changes
# Required Changes :recycle:
![almost-there](https://user-images.githubusercontent.com/93039359/178569876-9fcda5e8-6819-4569-95ee-acb393903a05.jpg)

### Hey @Irirwanirira :wave:

### Highlights :1st_place_medal:
 
:heavy_check_mark: Meaningful commits
:heavy_check_mark: Added .gitignore
:heavy_check_mark: Following Github Flow

Good job on implementing some of the changes requested by the previous reviewer, there are some issues that you still need to work on to go to the next project but you are almost there! :blush:

# Optional Suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @HAMMAS-SALEEM in your question so I can receive the notification. Otherwise reach out to me on slack which is more fast. You can reach out to me on slack by searching my name in **full-time-students** channel :+1:

_**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_

------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-18 08:32 UTC, HAMMAS-SALEEM commented on index.html
> +                </ul>
### Your Icons
![icons-fixable](https://user-images.githubusercontent.com/93039359/185346535-f50e885f-f924-497f-9bb5-882dc91ef764.png)

### Figma Icons
![figma-icons](https://user-images.githubusercontent.com/93039359/185346560-82158cd5-1163-4072-a378-01f5428b7342.png)

- [ ] You are not using the same icons from Figma template. Please use the same icons to follow the design as previous reviewer suggested :+1:

2022-08-18 08:32 UTC, HAMMAS-SALEEM commented on README.md
> +
**[Optional]**
- [ ] Please add your project name here because you readme is your documentation so please take it seriously :thinking:

2022-08-18 08:32 UTC, HAMMAS-SALEEM commented on README.md
> +
**[Optional]**
- [ ] Please fix the link to your issues page :+1:

2022-08-18 08:32 UTC, HAMMAS-SALEEM commented on index.html
> +    </header>
### Your Header
![margin (copy)](https://user-images.githubusercontent.com/93039359/185348146-2c106237-c819-42ea-9d56-3c204f350da2.png)

### Figma Header
![figma-header](https://user-images.githubusercontent.com/93039359/185348167-7719961a-7061-499f-acf1-f8b4080b7f59.png)

**[Optional]**
- [ ] Your header should have a **margin-top** to match the Figma template :+1:

2022-08-18 08:32 UTC, HAMMAS-SALEEM commented on README.md
> +This project is [MIT](./LICENSE) licensed.
**[Optional]**
- [ ] You have a link to your **LICENSE** file but where is your license file :thinking: You didn't add it yet please add it using these [guidlines](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository) :+1:

2022-08-18 08:38 UTC, HAMMAS-SALEEM requested changes

2022-08-18 08:38 UTC, HAMMAS-SALEEM commented on .hintrc
> +}
![pr-title](https://user-images.githubusercontent.com/93039359/185349904-a0f31d20-3c92-462f-893f-e3733dff4e33.png)

**[Optional]**
- [ ] Your PR has a title that is not so descriptive enough. Because **My Portfolio** is not describing what are you doing in the project. PR title fully describes what is happening in this branch. You could use **Portfolio: setup and mobile first** for your PR title. :+1:

2022-08-18 08:38 UTC, HAMMAS-SALEEM commented on .hintrc
> +}
**Branch name**
![pr-title (copy)](https://user-images.githubusercontent.com/93039359/185350210-22e731b3-2c88-49c5-8fce-cbf91562559b.png)
**[Optional]**
- [ ] Your branch name is not descriptive enough. You are using **new-branch**, you can use  **feature/mobile-first-portfolio** or **feature/initialize-hello-microverse** :+1:

2022-08-18 21:52 UTC, ha-manel approved these changes
# STATUS: APPROVED ✅
## Hi @Irirwanirira 👋

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
**Congratulations! 🎉**

<img src="https://media4.giphy.com/media/26DOoDwdNGKAg6UKI/giphy-downsized-medium.gif"/> 

## Highlights:
* Well written PR description ✔️ 
* All tests passed ✔️ 

------
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-18 21:54 UTC, merged