Project: Mobile-Portofolio-Contact section
Irirwanirira/My-portofolio pull request #8
Opened 2022-08-23 19:37 UTC by Irirwanirira

## My PR composed of:

 - Pair programing 
 - Added HTML 
 - styled with css
 - Modified with contributors
 - Checked the linters 

### Thank you for reviewing my project

2022-08-23 20:44 UTC, BenMukebo requested changes
### Hi @Irirwanirira,

You did a great job so far 👏🏼 👏🏼
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

### To highlight 💪🏻

- Flexbox was used to layout the elements.. ✔️ 
- GitHub flow was correctly used.  ✔️ 
- All validations described in the project description are working on form submission.🥇 
- The form is submitted successfully with valid input values. 👏🏻 
 👍  Good job!


## STATUS: CHANGES REQUESTED  ♻️ 
_Please Check the comments under the review and make all required changes_

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


- [OPTIONAL]  Please let's make sure that contributions to a group project are distributed equally among the members (commit messages should be fairly equal).


Cheers and Happy coding!👏👏👏 💻  
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me @BenMukebo when you comment so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-23 20:44 UTC, BenMukebo commented on README.md
>  - Twitter: [@Iri_joseph](https://twitter.com/Irirwanirira)
- [ ] It will be nice to add explicit steps to clone and run your project locally, as this will be of help to non-technical users. You can put the steps to clone and run the project in a new Getting Started section under the project's description. This includes `git clone URL` , `cd project_name`, etc 🙃  Please refer to this [template](https://github.com/microverseinc/readme-template), you can copy and paste the content but remember to customize it to your project.

- [ ] Please remove all unnecessary titles since they are empty  or add details to them (Prerequisites, run tests Deployment ....) 🚮 

- The README file It is the first file a person will see when they encounter your project, so it should be fairly brief but detailed. It will make your project stand out from a bunch of others.

2022-08-23 20:44 UTC, BenMukebo commented on index.html
> +    </section>
- [ ] Great job so far on your form 👏🏻 However there are two missing requirements, kindly make sure to address them:

1. You should sticks to the design templates in Figma as much as possible, this includes the font, colors, images, and spacing (margin/padding)
  - You need to add more margin-bottom after the `Get it touch` button 👍🏻 

![18](https://user-images.githubusercontent.com/79058364/186258722-977176d6-ade1-4356-adce-328741c20218.png)

2. Button interactions such as hover, active (when it's pressed), disabled, and enable (default state) are styled as shown in the Figma template.
 - Please use this image below 👇🏻 to improve the background of your  `Get it touch` button 👍🏻 

<img width="602" alt="Screen Shot 2022-08-19 at 10 22 09 PM" src="https://user-images.githubusercontent.com/83717285/185727145-0e9f990b-d2ca-4d2d-99a4-2b88a4f36f63.png">

2022-08-23 22:46 UTC, cynthiainga requested changes
Hi @Irirwanirira, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
![](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

 ## Highlights

- [x] All linters are passing ✔️ 
- [ ] You have a descriptive Pull Request ✔️ 
- [x] You used the correct Github flow ✔️ 
- [ ] Good design 👍

 ## Required Changes ♻️

- [x] Please kindly check the comments under the review 👇 👇

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-23 22:46 UTC, cynthiainga commented on README.md
> -## Getting Started
- [ ] As mentioned by the previous reviewer, it is a good idea to add explicit steps to clone and run the project locally, as this will be helpful to non-technical users. You can put the steps to clone and run the project in a new `Getting Started section` under the project's description. This includes `git clone URL`, cd project_name, etc 🙃

2022-08-24 06:26 UTC, Irirwanirira commented on README.md
> -## Getting Started
## Done

2022-08-24 06:41 UTC, sumairq approved these changes
### Hi Team , 

<img src="https://media4.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✔️ Good commit history
✔️Linters are passing
✔️Very professional README
✔️Correct Github flow
✔️Descriptive PR
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-24 06:50 UTC, merged