Project: personal - Porto-folio media query.
Irirwanirira/My-portofolio pull request #9
Opened 2022-08-25 10:41 UTC by Irirwanirira

## My PR is composed of 

 - I added HTML content 
 - I styled it using CSS 
 - I added some images

### Thank you for reviewing my Project

2022-08-25 13:51 UTC, HAMMAS-SALEEM requested changes
# Required Changes :recycle:
![almost-there](https://user-images.githubusercontent.com/93039359/178569876-9fcda5e8-6819-4569-95ee-acb393903a05.jpg)

### Hey @Irirwanirira :wave:

### Highlights :1st_place_medal:
 
:heavy_check_mark: Meaningful commits
:heavy_check_mark: Added .gitignore
:heavy_check_mark: Following GitHub Flow

Good job on implementing some of the requirements, there are some issues that you still need to work on to go to the next project but you are almost there! :blush:

# Optional Suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @HAMMAS-SALEEM in your question so I can receive the notification. Otherwise reach out to me on slack which is more fast. You can reach out to me on slack by searching my name in **full-time-students** channel :+1:

_**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_

------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-25 13:51 UTC, HAMMAS-SALEEM commented on index.html
### Your Title
![student-title](https://user-images.githubusercontent.com/93039359/186671085-359a0a07-5200-4015-be33-714a9bdf6d89.png)

### Figma Titie
![figma-title](https://user-images.githubusercontent.com/93039359/186671113-57b54e9b-485e-472a-9c26-ff0fa917f226.png)

- [x] Your title should be in two lines in the desktop version as shown in the Figma template :blush:
- [x] Also, it should have margin-top then it won't collide the the background image which is making it look not professional :thinking:

2022-08-25 13:51 UTC, HAMMAS-SALEEM commented on index.html
### Your Paragraph
![student-paragrpah](https://user-images.githubusercontent.com/93039359/186671458-5c9a0ca2-c273-411c-98d8-121952eee1e7.png)

### Figma Paragraph
![figma-paragraph](https://user-images.githubusercontent.com/93039359/186671489-52ad682a-312d-4f96-8f3f-409ad40ed33d.png)

- [ ] Your paragraph should be in 2 - 3 lines in the desktop version as shown in the Figma template :+1: Please make this change to make your project look professional :blush:

2022-08-25 13:51 UTC, HAMMAS-SALEEM commented on index.html
> +                </div>
### Your Margins
![margin-missing](https://user-images.githubusercontent.com/93039359/186673106-9094d628-b04c-463c-8060-3b3bf7f85c48.png)

### Figma Margins
![margin-fixed (copy)](https://user-images.githubusercontent.com/93039359/186673292-52067141-cb73-479c-81b1-e504d4b81248.png)

- [ ] Please add the margins shown in the Figma image with the red lines :+1: Please follow the Figma template to make your project look professional :+1:

2022-08-25 13:51 UTC, HAMMAS-SALEEM commented on index.html
> +
### Your Title
![project-title-color](https://user-images.githubusercontent.com/93039359/186673976-f1cdfe57-7893-4410-be01-90178506a1f9.png)

- [ ] Your are not using the right color for your title. The right color is **#091E42**. Please use it to make your project look like Figma template :+1:

2022-08-25 13:51 UTC, HAMMAS-SALEEM commented on index.html
> +
### Your Project Paragrpah
![student-project-par](https://user-images.githubusercontent.com/93039359/186676929-6618fb5f-9f5d-477a-b56c-ac83be5bb3ed.png)

### Figma Project Paragraph
![figma-project-par](https://user-images.githubusercontent.com/93039359/186676965-db98ec9e-5d80-42fc-8600-90267f97bac0.png)


- [ ] Your paragraph should be a little bit more bold as shown in the Figma template to make it easily readable for low vision people :+1:

2022-08-25 13:51 UTC, HAMMAS-SALEEM commented on index.html
> +                    </div>
### Your Tech
![student-project-tech](https://user-images.githubusercontent.com/93039359/186677236-8bb0edbc-4bfb-4dc0-8f15-d1d13a054e36.png)

### FIgma Tech
![figma-project-tech](https://user-images.githubusercontent.com/93039359/186677273-4a586c4e-02f7-4ddd-9ba6-6d42e7ddb102.png)

- [ ] Your styling for the tech is not very similar to the Figma template such as **background-color** and **border-radius**. Please follow the Figma template to make it professional :+1:

2022-08-25 13:51 UTC, HAMMAS-SALEEM commented on index.html
> +
![button-effects (copy)](https://user-images.githubusercontent.com/93039359/186677949-3ca7e541-c576-42b9-b507-265f0c376f8f.png)

- [ ] Your buttons should have all the effects as shown in the Figma button effects. Please implement them to make your design look professional :blush:

2022-08-25 13:51 UTC, HAMMAS-SALEEM commented on index.html
> +
### Your button
![third-card-button](https://user-images.githubusercontent.com/93039359/186679247-5c507c13-1313-49c0-af6a-68a1e639c6a7.png)

- [ ] In the third card you have styled your button in a different way as shown in the Figma template. This blue background-color will show up when you will hover on this button.Other than that this button will be similar to other. Now you can ask then why it is shown in the Figma template. So the reason for showing in the Figma template is to give you an idea how it would look like. :thinking: These are effects which you have to implement as shown below :arrow_down:
![button-effects (copy)](https://user-images.githubusercontent.com/93039359/186679346-b515ac54-829e-463a-95ef-005bb5a64024.png)

2022-08-25 13:51 UTC, HAMMAS-SALEEM commented on index.html
### Your About me Section
![full-screen1 (copy)](https://user-images.githubusercontent.com/93039359/186682899-fa61b8c2-a180-48c7-b003-b05c57b58d28.png)


### Figma About me Section
![figma-full-screen2](https://user-images.githubusercontent.com/93039359/186682362-6b8f208f-ea70-4526-8331-8f0e4f5b6312.png)


- [ ] Please make the changes as shown in the Image above to make it look professional :+1: because your design is lacking a lot of things in following the Figma template :fearful:

2022-08-25 20:29 UTC, Irirwanirira commented on index.html
Done, Thank you

2022-08-25 20:30 UTC, Irirwanirira commented on index.html
> +                    </div>
Done, Thank you

2022-08-25 20:30 UTC, Irirwanirira commented on index.html
> +
Well Adjusted

2022-08-25 20:30 UTC, Irirwanirira commented on index.html
> +
Issue fixed

2022-08-25 20:31 UTC, Irirwanirira commented on index.html
The content was resised, Thank you

2022-08-25 20:32 UTC, Irirwanirira commented on index.html
@HAMMAS-SALEEM  Thank you for your comments, all the addressed issues were corrected.

2022-08-25 21:41 UTC, Abenezer-Tilahun requested changes
Hi @Irirwanirira   

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


## Highlights

✔️ No linter errors.
✔️ You used correct Github Flow.
✔️ Professional README 

![almost](https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif)

## Required Changes ♻️
_Check the comments below the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-25 21:41 UTC, Abenezer-Tilahun commented on index.html
>              </p>
- [ ] Kindly, try to align `p`  to center just like the Figma design .

Your project Look Likes this : 
![contac](https://user-images.githubusercontent.com/93598189/186771775-b7af7c8e-a89c-4de3-910c-6e8bbd02eba1.PNG)

The Figma design Look likes this : 

![fir1](https://user-images.githubusercontent.com/93598189/186771855-b6681a97-747b-4d55-9a91-bc937ace0b1c.PNG)

2022-08-25 21:41 UTC, Abenezer-Tilahun commented on style.css
> +
- [ ] Kindly, make sure  that mobile design still looks like expected, For Minimum mobile screen size should be 375px, at 375px the "Work section " is not visible and responsive.

For Mobile screen size your Project Look likes this : 
![work](https://user-images.githubusercontent.com/93598189/186772666-f07dcd21-513b-40f1-913b-35f771371454.PNG)

2022-08-25 21:41 UTC, Abenezer-Tilahun commented on style.css
> +
- [ ] Good Job for Implementing the previous reviewer suggestion. But Still I recoomend you to stick to the design as much as possible (e.g., font, colors, images, text, margins) using [the info of the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1).
- [ ] Please make sure that for "contact" section in Desktop and mobile screen size you follow the Figma design.

Your "contact" section for desktop and mobile screen size look likes this :
Desktop screen size 
![bot](https://user-images.githubusercontent.com/93598189/186773683-9d873f65-7b18-47c0-afef-a3d968fa9a2f.PNG)

Mobile screen size 
![c1](https://user-images.githubusercontent.com/93598189/186773690-b512230c-beb1-4f3d-949f-80ef9ed0edec.PNG)
![c12](https://user-images.githubusercontent.com/93598189/186773714-37df7391-2ec0-4b52-a1cb-12c37fffa724.PNG)

2022-08-25 21:59 UTC, Irirwanirira commented on style.css
> +
@Abenezer-Tilahun  ohh, I commented some part of HTML to have good focus, an di forgot to comment it out before i commit,

2022-08-25 22:05 UTC, Irirwanirira commented on index.html
>              </p>
Done

2022-08-25 22:18 UTC, Irirwanirira commented on style.css
> +
@Abenezer-Tilahun under the button we need enough space because when we start to fill the form the keyboard occupies some of the space and we remain with 80px  before the button exit the footer section, kindly reach me via comments for further explanation

2022-08-25 22:56 UTC, Irirwanirira commented on index.html
>              </p>
please, Below is the picture of my desktop version with p aligned to the center.

![download](https://user-images.githubusercontent.com/105460631/186780745-5c0961a9-8c80-47d3-8a26-930556c8a895.png)

2022-08-25 22:56 UTC, Irirwanirira commented on style.css
> +
## below is the picture of my desktop version, it doesn't have that line you showed above 
![download](https://user-images.githubusercontent.com/105460631/186781426-b3262cf9-af6c-465d-b0f5-374f1898eda5.png)

## below is my mobile version with small margin at the bottom, issue solved 

![download](https://user-images.githubusercontent.com/105460631/186782642-ee29af52-bd68-4435-9eff-3ed4542e9635.png)

2022-08-25 23:11 UTC, Irirwanirira commented on style.css
> +
#issues solve
![download](https://user-images.githubusercontent.com/105460631/186783523-43419205-f28e-4d29-9443-35bdcb351c8c.png)
d

2022-08-26 00:05 UTC, franclobo reviewed
Hi @Irirwanirira, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that hasn't run the linters. 👇🏽 

![image](https://user-images.githubusercontent.com/58642949/186789561-907be0c7-f462-4aaa-9e6e-938d5e0a44bc.png)


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-08-26 06:24 UTC, mgmediaweb commented on index.html
Good job following the advice of the previous reviewer

2022-08-26 06:25 UTC, mgmediaweb commented on index.html
Good job following the advice of the previous reviewer

2022-08-26 06:26 UTC, mgmediaweb commented on index.html
> +
Good job following the advice of the previous reviewer

2022-08-26 06:27 UTC, mgmediaweb commented on index.html
> +
Good job following the advice of the previous reviewer

2022-08-26 06:28 UTC, mgmediaweb commented on index.html
> +
Good job following the advice of the previous reviewer

2022-08-26 06:30 UTC, mgmediaweb commented on index.html
Good job following the advice of the previous reviewer

2022-08-26 06:31 UTC, mgmediaweb commented on index.html
>              </p>
Good job following the advice of the previous reviewer

2022-08-26 06:36 UTC, mgmediaweb approved these changes
Hi @Irirwanirira , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![approved4](https://user-images.githubusercontent.com/41912912/186838037-9b380b54-dd24-49c9-898d-d99ceb5a80ed.gif)

## Highlights 💯 
- Good job following the advice of the previous reviewer ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-26 06:53 UTC, merged